In [20]:
import torch
from torch.autograd import Variable
import torchvision.transforms as transforms
import torchvision.datasets as dsets
import numpy as np

from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_model
from gpytorch.mlls import ExactMarginalLogLikelihood
from botorch.acquisition import qUpperConfidenceBound
from botorch.optim import sequential_optimize, joint_optimize
from botorch.utils.sampling import manual_seed

In [21]:
train_dataset = dsets.MNIST(root='./data', train=True, transform=transforms.ToTensor(), download=True)
test_dataset = dsets.MNIST(root='./data', train=False, transform=transforms.ToTensor(), download=True)

In [22]:
torch.manual_seed(0)
torch.cuda.manual_seed(0)
np.random.seed(0)

In [23]:
batch_size = 100
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=False)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False)

In [24]:
class LogisticRegression(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LogisticRegression, self).__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)

    def forward(self, x):
        outputs = self.linear(x)
        return outputs

In [25]:
class MultiLayerNN(torch.nn.Module):
    def __init__(self, input_dim, hidden_units_dim, output_dim):
        super(MultiLayerNN, self).__init__()
        self.model = torch.nn.Sequential(
            torch.nn.Linear(input_dim, hidden_units_dim),
            torch.nn.ReLU(),
            torch.nn.BatchNorm1d(hidden_units_dim),
            torch.nn.Linear(hidden_units_dim, hidden_units_dim),
            torch.nn.ReLU(),
            torch.nn.BatchNorm1d(hidden_units_dim),
            torch.nn.Linear(hidden_units_dim, hidden_units_dim),
        )
        for m in self.model:
            if isinstance(m, torch.nn.Linear):
                torch.nn.init.kaiming_normal_(m.weight)
                torch.nn.init.constant_(m.bias, 0)
        
    def forward(self, x):
        return self.model(x)

In [26]:
batch_size = 100
epochs = 30
input_dim = 784
output_dim = 10
lr_rate = 0.05
z_dim = 5
z_length = 50
len_train_dataset = len(train_loader.dataset)

In [27]:
model = MultiLayerNN(input_dim, 1000, output_dim).cuda()
alt_model = MultiLayerNN(input_dim, 1000, output_dim).cuda()
criterion = torch.nn.CrossEntropyLoss().cuda()

In [33]:
def _seperate_w(w, model):
    w_reshape_list = []
    num_params = 0
    for param in model.parameters():
        w_reshape = w[num_params:num_params + param.shape.numel()].reshape_as(param)
        w_reshape_list.append(w_reshape)
        num_params += param.shape.numel()
    
    return w_reshape_list

def _get_w_set(w, model):
    w_set = [_seperate_w(w[:, i].cuda(), model) for i in range(w.shape[1])]
    return w_set

def _get_w(A, z, c, d):
    sig = torch.nn.Sigmoid()
    lr_rate = z.transpose(0, 1)[:, 0]
    lr_rate = (d - 1) * lr_rate + 1
    h = 2 * sig(c * A.mm(z[1:, :]))
    return lr_rate * h.clamp(min=1.0)

def _get_alt_model_loss(x, y, model, alt_model, criterion, w_set):
    alt_losses = []
    
    for w_reshape in w_set:
        for param, alt_param, w in zip(model.parameters(), alt_model.parameters(), w_reshape):
            #print(param.shape, alt_param.shape, w.shape, param.grad.shape)
            alt_param.data = param.data - lr_rate * w.data * param.grad.data
            #alt_param.data = param.data - lr_rate * (1) * param.grad.data
        
        alt_outputs = alt_model(x)
        alt_loss = criterion(alt_outputs, y)

        alt_losses.append(alt_loss)

    return torch.tensor(alt_losses)

class AdaptiveGPGradient:
    def __init__(self, model, z_dim, z_length, update_weight_step, fit_gp_step):
        w_dim = sum([param.shape.numel() for param in model.parameters()])
        
        self.A = torch.randn([w_dim, z_dim - 1])
        self.Z = torch.rand([z_dim, z_length])
        
        self.model = model
        
        self.step = 0
        self.update_weight_step = update_weight_step
        self.fit_gp_step = fit_gp_step
        
        self.c = 1.0
        self.d = 10.0
        
        self.z_length = z_length
        self.z_dim = z_dim
        
        self.W = _get_w(self.A, self.Z, self.c, self.d)
        self.w_set = _get_w_set(self.W, model)
        self.V = torch.zeros(self.z_length)
        
        self.best_z = torch.zeros([z_dim ,1])
        self.best_w = _get_w_set(_get_w(self.A, self.best_z, self.c, self.d), self.model)[0]
        #self.fit_gp_step = fit_gp_step
    
    def gather_V(self, images, labels, model, criterion):
        with torch.no_grad():
            V = _get_alt_model_loss(images, labels, model, self.model, criterion, self.w_set)
            best_V = _get_alt_model_loss(images, labels, model, self.model, criterion, [self.best_w])
            self.V += (best_V - V) / self.update_weight_step
            #print(self.V)
        
    def update_Z(self):
        if self.step < self.update_weight_step:
            self.step += 1
            return
        else:
            self.step = 0
            print(self.V)
        
        train_X = self.Z.transpose(0, 1).cpu().data
        train_X = torch.cat([train_X, self.best_z.reshape([1, -1])], 0)
        
        train_Y = self.V.reshape([-1, 1]).data
        train_Y = torch.cat([train_Y, torch.zeros([1, 1])], 0)
        train_Y = (train_Y - train_Y.min()) / (train_Y.max() - train_Y.min())
        
        with manual_seed(0):
            gp = SingleTaskGP(train_X, train_Y)
            mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
            fit_gpytorch_model(mll)

            qUCB = qUpperConfidenceBound(gp, beta=0.1)

            z_dim = self.Z.shape[0]
            bounds = torch.stack([torch.zeros(z_dim), torch.ones(z_dim)])

            # Get best_z
            self.best_z, _ = joint_optimize(
                qUCB, bounds=bounds, q=1, num_restarts=20, raw_samples=512,
            )
        self.best_z.transpose_(0, 1)
        self.best_w = _get_w_set(_get_w(self.A, self.best_z, self.c, self.d), self.model)[0]
        
        # Get candidates
        arg_sorted = train_Y.reshape([-1]).argsort()
        arg_sorted = arg_sorted[1:]
        self.Z = train_X[arg_sorted].transpose(0, 1)
        W = _get_w(self.A, self.Z, self.c, self.d)
        self.w_set = _get_w_set(W, model)
        
        # Reset V
        self.V = torch.zeros(self.z_length)
        print(self.Z.transpose(0, 1))
        
test = AdaptiveGPGradient(alt_model, z_dim, z_length, 100, 1)

In [34]:
def show_params(model):
    for param in model.parameters():
        print(param.data)

In [35]:
results = []
adaptive_gp_gradient = AdaptiveGPGradient(alt_model, z_dim, z_length, 100, 1)

for epoch in range(epochs):
    avg_loss = 0.
    
    increments = torch.zeros(z_length)
    
    for i, (images, labels) in enumerate(train_loader):
        images = Variable(images.view(-1, 28 * 28)).cuda()
        labels = Variable(labels).cuda()
        
        outputs = model(images)
        loss = criterion(outputs, labels)

        model.zero_grad()
        loss.backward()
        
        avg_loss += loss / (len_train_dataset / batch_size)
        
        with torch.no_grad():
            adaptive_gp_gradient.gather_V(images, labels, model, criterion)
            for w, param in zip(adaptive_gp_gradient.best_w, model.parameters()):
                param.data -= lr_rate * w.data * param.grad.data
        
        adaptive_gp_gradient.update_Z()
    results.append(avg_loss)
    
    print(epoch, avg_loss.data)
    

tensor([ 0.0327,  0.0441,  0.0080, -0.0181,  0.0435,  0.0460,  0.0428,  0.0461,
        -0.0023,  0.0239,  0.0121,  0.0094,  0.0287,  0.0339,  0.0460,  0.0443,
         0.0272,  0.0452,  0.0461,  0.0460,  0.0127,  0.0141,  0.0197, -0.0068,
         0.0163,  0.0385,  0.0234,  0.0246,  0.0162,  0.0418,  0.0429,  0.0242,
         0.0198,  0.0461,  0.0301, -0.0192,  0.0452,  0.0460,  0.0410,  0.0263,
         0.0410,  0.0372,  0.0447, -0.0080,  0.0461,  0.0364,  0.0435,  0.0140,
         0.0352,  0.0184])
tensor([[9.8072e-01, 8.4359e-02, 8.3079e-01, 5.8914e-01, 9.6839e-01],
        [9.2766e-01, 6.3870e-01, 7.9743e-01, 1.9470e-01, 8.6792e-01],
        [9.4674e-01, 6.9452e-01, 5.6195e-01, 6.6222e-01, 1.4673e-01],
        [9.6476e-01, 3.9471e-01, 5.9279e-01, 1.8843e-01, 1.7079e-01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.0318e-01, 4.4584e-01, 3.4564e-01, 2.2082e-01, 3.1590e-01],
        [8.0913e-04, 5.1878e-01, 1.2082e-01, 6.7800e-01, 4.9150e-01],
   

tensor([[9.4674e-01, 6.9452e-01, 5.6195e-01, 6.6222e-01, 1.4673e-01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.6476e-01, 3.9471e-01, 5.9279e-01, 1.8843e-01, 1.7079e-01],
        [8.0913e-04, 5.1878e-01, 1.2082e-01, 6.7800e-01, 4.9150e-01],
        [9.0318e-01, 4.4584e-01, 3.4564e-01, 2.2082e-01, 3.1590e-01],
        [1.8829e-04, 8.9104e-01, 9.1278e-01, 5.6687e-01, 7.4393e-01],
        [7.8043e-01, 9.7217e-01, 5.6940e-01, 7.9250e-01, 5.9985e-01],
        [7.9057e-01, 9.1008e-02, 7.5588e-01, 9.6191e-01, 3.4282e-01],
        [7.7018e-01, 8.7775e-01, 9.7685e-01, 4.5194e-01, 5.4957e-01],
        [8.0248e-01, 3.9792e-01, 5.9638e-01, 3.8748e-01, 5.0339e-01],
        [7.5308e-01, 9.5779e-01, 4.0928e-01, 8.1684e-01, 7.1736e-01],
        [7.6203e-01, 5.7109e-01, 6.0378e-02, 5.3277e-01, 8.8945e-01],
        [7.5247e-01, 1.6485e-01, 8.1469e-01, 7.6826e-01, 3.3236e-01],
        [7.5344e-01, 1.9061e-02, 5.7244e-01, 7.0895e-01, 7.2229e-01],
        [3.8496e-02,

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.0318e-01, 4.4584e-01, 3.4564e-01, 2.2082e-01, 3.1590e-01],
        [7.8043e-01, 9.7217e-01, 5.6940e-01, 7.9250e-01, 5.9985e-01],
        [7.9057e-01, 9.1008e-02, 7.5588e-01, 9.6191e-01, 3.4282e-01],
        [8.0913e-04, 5.1878e-01, 1.2082e-01, 6.7800e-01, 4.9150e-01],
        [7.7018e-01, 8.7775e-01, 9.7685e-01, 4.5194e-01, 5.4957e-01],
        [8.0248e-01, 3.9792e-01, 5.9638e-01, 3.8748e-01, 5.0339e-01],
        [7.5308e-01, 9.5779e-01, 4.0928e-01, 8.1684e-01, 7.1736e-01],
        [1.8829e-04, 8.9104e-01, 9.1278e-01, 5.6687e-01, 7.4393e-01],
        [7.6203e-01, 5.7109e-01, 6.0378e-02, 5.3277e-01, 8.8945e-01],
        [7.5247e-01, 1.6485e-01, 8.1469e-01, 7.6826e-01, 3.3236e-01],
        [7.5344e-01, 1.9061e-02, 5.7244e-01, 7.0895e-01, 7.2229e-01],
        [6.9737e-01, 9.8295e-01, 8.0963e-01, 4.2114e-01, 3.7545e-01],
        [6.8151e-01, 8.6364e-01, 8.6325e-01, 7.8081e-01, 6.4854e-01],
        [7.2126e-01,

tensor([[1.8829e-04, 8.9104e-01, 9.1278e-01, 5.6687e-01, 7.4393e-01],
        [9.0318e-01, 4.4584e-01, 3.4564e-01, 2.2082e-01, 3.1590e-01],
        [7.8043e-01, 9.7217e-01, 5.6940e-01, 7.9250e-01, 5.9985e-01],
        [7.9057e-01, 9.1008e-02, 7.5588e-01, 9.6191e-01, 3.4282e-01],
        [7.7018e-01, 8.7775e-01, 9.7685e-01, 4.5194e-01, 5.4957e-01],
        [8.0248e-01, 3.9792e-01, 5.9638e-01, 3.8748e-01, 5.0339e-01],
        [7.5308e-01, 9.5779e-01, 4.0928e-01, 8.1684e-01, 7.1736e-01],
        [3.8496e-02, 6.4685e-01, 5.1635e-01, 1.8405e-01, 4.4886e-01],
        [7.6203e-01, 5.7109e-01, 6.0378e-02, 5.3277e-01, 8.8945e-01],
        [7.5247e-01, 1.6485e-01, 8.1469e-01, 7.6826e-01, 3.3236e-01],
        [7.5344e-01, 1.9061e-02, 5.7244e-01, 7.0895e-01, 7.2229e-01],
        [6.9737e-01, 9.8295e-01, 8.0963e-01, 4.2114e-01, 3.7545e-01],
        [6.8151e-01, 8.6364e-01, 8.6325e-01, 7.8081e-01, 6.4854e-01],
        [7.2126e-01, 2.8973e-02, 2.1017e-01, 9.9767e-01, 2.7731e-01],
        [6.4849e-02,

tensor([-1.2800e-02, -6.8778e-03, -1.2327e-02, -1.2229e-02, -1.1302e-02,
        -1.1239e-02, -4.8042e-03, -1.0315e-02, -9.8989e-03, -9.8045e-03,
        -8.1274e-03, -7.9576e-03, -7.8454e-03, -7.1615e-03, -2.1962e-03,
        -6.7909e-03, -5.5490e-03, -9.0458e-04, -4.5171e-03, -4.0780e-03,
        -3.9878e-04, -3.5365e-03, -1.1725e-04, -7.6184e-05, -2.6798e-05,
        -2.7801e-03,  1.7454e-04,  2.1939e-04, -2.2661e-03,  2.2361e-04,
         2.3182e-04,  3.0656e-04,  3.5993e-04, -1.3507e-03,  4.1317e-04,
         4.1741e-04,  4.2154e-04, -1.0892e-03,  4.1500e-04,  4.1329e-04,
         4.0069e-04,  3.9623e-04,  3.9691e-04, -7.2795e-04,  3.8752e-04,
         3.5744e-04,  3.5406e-04, -5.1221e-04, -4.9577e-04, -8.3137e-05])
tensor([[0.7906, 0.0910, 0.7559, 0.9619, 0.3428],
        [0.7702, 0.8778, 0.9769, 0.4519, 0.5496],
        [0.8025, 0.3979, 0.5964, 0.3875, 0.5034],
        [0.7531, 0.9578, 0.4093, 0.8168, 0.7174],
        [0.7620, 0.5711, 0.0604, 0.5328, 0.8895],
        [0.7525, 0.

tensor([-2.7828e-03, -7.8505e-03, -7.2514e-03, -7.1732e-03, -6.5694e-03,
        -6.2876e-03, -6.3475e-03, -1.4743e-03, -5.1517e-03, -5.0510e-03,
        -5.0099e-03, -4.5165e-03, -4.3038e-03, -3.4721e-03, -7.5503e-04,
        -2.7998e-03, -2.5057e-03, -2.1543e-03, -4.6947e-04, -1.6655e-03,
        -1.3420e-03, -3.1277e-04, -2.9015e-04, -2.6315e-04, -2.1679e-04,
        -7.7849e-04, -1.5088e-04, -1.2426e-04, -1.2284e-04, -1.1862e-04,
        -6.2835e-04, -7.4811e-05, -4.3215e-04, -3.9033e-05, -2.3898e-05,
        -3.1589e-04, -3.1549e-04,  6.8354e-06,  1.5854e-05,  2.2614e-05,
        -1.2287e-04,  3.0905e-05,  3.1305e-05, -8.8033e-05,  3.5276e-05,
         3.5967e-05,  3.4977e-05,  3.5572e-05,  3.1693e-05,  3.2609e-05])
tensor([[0.8025, 0.3979, 0.5964, 0.3875, 0.5034],
        [0.7531, 0.9578, 0.4093, 0.8168, 0.7174],
        [0.7620, 0.5711, 0.0604, 0.5328, 0.8895],
        [0.7525, 0.1648, 0.8147, 0.7683, 0.3324],
        [0.7534, 0.0191, 0.5724, 0.7089, 0.7223],
        [0.6974, 0.

tensor([-1.4028e-04, -5.2596e-03, -4.8114e-03, -4.5518e-03, -4.5125e-03,
         2.4635e-04, -3.7205e-03, -3.6418e-03, -3.4710e-03,  4.0273e-04,
        -3.1847e-03,  4.8763e-04, -2.9332e-03,  4.9993e-04,  5.1439e-04,
         5.3773e-04,  5.7109e-04, -2.3385e-03,  5.8264e-04,  5.8405e-04,
         5.8609e-04,  6.0454e-04,  6.1606e-04, -1.8623e-03,  6.1957e-04,
        -1.6549e-03,  6.2237e-04,  6.2141e-04,  6.1621e-04,  6.1300e-04,
        -1.3969e-03,  6.0847e-04,  6.0540e-04,  6.0126e-04,  5.9459e-04,
         5.8973e-04,  5.8771e-04,  5.7238e-04,  5.6920e-04,  5.6386e-04,
        -1.0361e-03, -8.2331e-04,  4.8600e-04,  3.4244e-04,  2.9976e-04,
        -3.6970e-04, -2.4204e-04,  8.0606e-05, -4.0797e-05,  7.5858e-05])
tensor([[0.7620, 0.5711, 0.0604, 0.5328, 0.8895],
        [0.7525, 0.1648, 0.8147, 0.7683, 0.3324],
        [0.7534, 0.0191, 0.5724, 0.7089, 0.7223],
        [0.6974, 0.9830, 0.8096, 0.4211, 0.3755],
        [0.6815, 0.8636, 0.8633, 0.7808, 0.6485],
        [0.7213, 0.

tensor([-7.4791e-04, -4.8910e-04, -4.5769e-04, -4.4020e-04, -7.8399e-04,
        -3.4516e-04, -3.0071e-04, -1.5569e-04, -5.4097e-04, -6.8600e-05,
        -4.2421e-04, -3.6610e-05, -4.1359e-06, -3.5072e-04, -3.3948e-04,
        -3.2553e-04, -3.0109e-04,  2.8690e-05, -2.6267e-04,  4.4541e-05,
        -2.4632e-04, -2.4474e-04, -2.4213e-04, -2.1151e-04, -1.8429e-04,
        -1.7154e-04, -1.6179e-04,  5.8551e-05, -1.5455e-04, -1.4030e-04,
         5.8532e-05, -1.2906e-04, -1.1670e-04, -1.0845e-04, -1.0007e-04,
        -9.6207e-05,  5.1647e-05, -8.8581e-05, -8.2230e-05,  5.0042e-05,
        -7.8103e-05, -7.4970e-05,  4.4878e-05,  4.5303e-05, -6.3813e-05,
        -6.1835e-05, -5.8080e-05, -2.3397e-05,  1.9894e-05,  1.2553e-05])
tensor([[0.7534, 0.0191, 0.5724, 0.7089, 0.7223],
        [0.1471, 0.6434, 0.7609, 0.1273, 0.1331],
        [0.6974, 0.9830, 0.8096, 0.4211, 0.3755],
        [0.6815, 0.8636, 0.8633, 0.7808, 0.6485],
        [0.7213, 0.0290, 0.2102, 0.9977, 0.2773],
        [0.1645, 0.

tensor([-8.3666e-04, -8.2748e-04, -7.1214e-04, -6.4500e-04, -4.6151e-04,
        -3.2148e-04, -2.5852e-04, -1.8605e-04, -8.4474e-05, -3.1722e-05,
         2.2371e-05,  5.2394e-05,  6.5059e-05, -3.2558e-04,  7.9839e-05,
         8.0307e-05,  8.1974e-05,  8.1876e-05, -2.3988e-04, -1.8548e-04,
        -1.7762e-04, -1.6724e-04,  7.4982e-05, -1.4893e-04,  7.1314e-05,
         6.3901e-05, -1.2088e-04, -1.0894e-04, -1.0732e-04, -1.0585e-04,
         5.0399e-05, -8.3125e-05, -6.3360e-05, -5.3904e-05, -4.6841e-05,
         2.4312e-05, -4.1635e-05,  2.6843e-05,  2.2850e-05,  1.6430e-05,
        -3.1780e-05,  1.5261e-05,  1.3328e-05,  9.9742e-06, -2.3654e-05,
         5.0249e-07, -1.4575e-05, -2.7496e-06,  5.1830e-06, -8.6959e-06])
tensor([[0.7213, 0.0290, 0.2102, 0.9977, 0.2773],
        [0.6888, 0.8966, 0.5759, 0.5459, 0.2459],
        [0.7038, 0.1905, 0.6579, 0.6466, 0.1735],
        [0.6528, 0.7088, 0.7377, 0.0699, 0.5560],
        [0.1471, 0.6434, 0.7609, 0.1273, 0.1331],
        [0.6250, 0.

tensor([ 1.6070e-04,  1.6255e-04,  1.6066e-04,  1.5874e-04,  1.5461e-04,
        -3.4299e-04,  1.4651e-04,  1.3940e-04, -2.6569e-04,  1.2980e-04,
        -2.1622e-04, -2.0872e-04, -1.9913e-04,  1.1933e-04, -1.8235e-04,
         1.1114e-04, -1.5600e-04, -1.4462e-04, -1.4355e-04, -1.4294e-04,
        -1.4175e-04,  9.7251e-05,  9.3262e-05, -1.2039e-04,  8.6334e-05,
         8.6352e-05,  8.3377e-05, -1.0112e-04, -9.1865e-05, -8.4999e-05,
        -7.9797e-05, -6.9524e-05,  5.8563e-05, -6.1410e-05,  5.1130e-05,
        -5.2387e-05, -4.6086e-05,  3.9964e-05, -3.9915e-05, -3.6943e-05,
        -3.7040e-05, -3.1369e-05, -2.6295e-05, -2.3269e-05, -2.0890e-05,
        -1.9365e-05,  2.0252e-05, -1.2199e-05, -1.0418e-05, -7.5896e-06])
tensor([[0.1645, 0.9595, 0.2677, 0.6715, 0.7897],
        [0.1935, 0.7704, 0.3745, 0.7665, 0.1302],
        [0.2030, 0.2764, 0.2765, 0.2224, 0.8799],
        [0.1922, 0.8781, 0.2159, 0.6896, 0.9611],
        [0.2144, 0.5943, 0.7892, 0.2774, 0.0339],
        [0.2296, 0.

tensor([-9.1255e-05, -2.5380e-06,  3.0077e-05,  6.1439e-05,  9.7499e-05,
         1.1539e-04,  1.2704e-04,  1.3525e-04,  1.3720e-04,  1.3681e-04,
         1.3593e-04,  1.3406e-04,  1.3434e-04,  1.3263e-04,  1.2030e-04,
         1.1590e-04,  1.0854e-04,  1.0095e-04, -1.8546e-04,  9.3646e-05,
        -1.3261e-04, -1.2443e-04, -1.1466e-04,  7.7503e-05,  7.1896e-05,
        -9.7035e-05,  6.9547e-05,  6.7767e-05,  6.2090e-05,  6.0476e-05,
        -6.9682e-05,  5.5867e-05,  5.8032e-05,  5.1915e-05, -5.8101e-05,
        -5.6575e-05, -5.5399e-05, -5.7271e-05,  4.5965e-05,  4.3498e-05,
         3.7995e-05,  4.5979e-05, -3.4049e-05,  2.3899e-05,  3.2051e-05,
         1.6086e-05, -1.4863e-05, -5.6040e-06,  6.0978e-06,  8.2760e-07])
tensor([[0.1935, 0.7704, 0.3745, 0.7665, 0.1302],
        [0.2030, 0.2764, 0.2765, 0.2224, 0.8799],
        [0.1922, 0.8781, 0.2159, 0.6896, 0.9611],
        [0.2144, 0.5943, 0.7892, 0.2774, 0.0339],
        [0.6528, 0.7088, 0.7377, 0.0699, 0.5560],
        [0.2296, 0.

tensor([-7.2021e-06,  7.4455e-06,  2.8627e-05,  3.9897e-05, -1.8572e-04,
         4.9222e-05, -1.7929e-04, -1.7055e-04, -1.5589e-04,  5.3534e-05,
         5.4857e-05, -1.3259e-04,  5.5363e-05, -1.2294e-04, -1.2116e-04,
        -1.2124e-04, -1.2001e-04,  5.3815e-05,  5.2947e-05, -1.0110e-04,
         5.0262e-05,  5.0378e-05,  4.9690e-05, -8.5169e-05, -7.7414e-05,
        -7.3126e-05, -7.1405e-05, -6.7102e-05, -6.1810e-05, -5.8680e-05,
        -5.1728e-05,  3.7653e-05, -4.3916e-05,  3.3267e-05, -3.9167e-05,
        -3.4058e-05,  2.5879e-05, -3.1782e-05, -3.1274e-05, -2.7078e-05,
         1.9060e-05, -2.3287e-05, -1.8456e-05, -2.0239e-05, -1.7693e-05,
        -1.1719e-05, -1.0693e-05,  1.2638e-05, -8.4793e-06, -2.4694e-06])
tensor([[0.2030, 0.2764, 0.2765, 0.2224, 0.8799],
        [0.1922, 0.8781, 0.2159, 0.6896, 0.9611],
        [0.2144, 0.5943, 0.7892, 0.2774, 0.0339],
        [0.2296, 0.4200, 0.5547, 0.3822, 0.6251],
        [0.2270, 0.1022, 0.5698, 0.9564, 0.5873],
        [0.2416, 0.

tensor([-1.2634e-04, -1.8995e-04, -1.1229e-04, -9.2086e-05, -1.5935e-04,
        -8.2925e-05, -8.2089e-05, -8.1779e-05, -8.1359e-05, -6.5621e-05,
        -5.2071e-05, -4.5555e-05, -1.1537e-04, -4.2473e-05, -4.1457e-05,
        -3.7583e-05, -3.4254e-05, -3.1735e-05, -2.6828e-05, -2.2323e-05,
        -8.6262e-05, -1.8441e-05, -1.7024e-05, -1.4755e-05, -1.4022e-05,
        -1.2337e-05, -1.0176e-05, -7.0784e-06, -6.0495e-06, -7.1360e-06,
        -2.4753e-06, -4.5215e-06, -1.6020e-06, -5.4300e-05,  5.7926e-07,
         1.2868e-06,  6.7612e-06, -3.8110e-05,  9.1823e-06, -2.6247e-05,
         6.2384e-06, -1.8898e-05, -1.3662e-05,  8.0955e-06,  9.2862e-06,
        -8.0543e-06, -6.6313e-06, -2.7750e-06, -2.4831e-06,  1.2336e-06])
tensor([[0.6490, 0.4379, 0.1155, 0.2169, 0.2706],
        [0.1922, 0.8781, 0.2159, 0.6896, 0.9611],
        [0.5894, 0.1164, 0.3290, 0.3467, 0.7111],
        [0.2144, 0.5943, 0.7892, 0.2774, 0.0339],
        [0.2296, 0.4200, 0.5547, 0.3822, 0.6251],
        [0.5409, 0.

tensor([-9.2979e-05, -5.8926e-05, -3.1673e-05, -1.1348e-05, -5.2438e-06,
         8.0404e-07,  7.0213e-06,  1.3553e-05, -1.4643e-04,  1.9574e-05,
         1.8576e-05,  2.1834e-05, -1.3193e-04,  2.5711e-05,  2.5043e-05,
        -1.0902e-04, -9.9360e-05, -9.8574e-05, -9.8153e-05, -9.7014e-05,
         2.9582e-05, -7.9063e-05,  3.0594e-05,  3.0305e-05, -6.3114e-05,
        -5.5569e-05,  2.8612e-05, -5.0013e-05, -5.1085e-05, -4.5749e-05,
         2.5219e-05, -4.0946e-05, -3.7497e-05,  2.1653e-05, -3.1082e-05,
        -2.4110e-05, -1.9693e-05, -1.2876e-05,  1.1410e-05, -1.3097e-05,
        -1.5046e-05, -3.3443e-06, -1.6009e-06,  1.3400e-05, -8.6970e-06,
         6.6825e-06,  4.0521e-06, -5.5752e-06, -7.9374e-07,  5.0670e-06])
tensor([[0.2144, 0.5943, 0.7892, 0.2774, 0.0339],
        [0.2296, 0.4200, 0.5547, 0.3822, 0.6251],
        [0.2270, 0.1022, 0.5698, 0.9564, 0.5873],
        [0.2553, 0.4794, 0.0731, 0.3782, 0.0968],
        [0.2416, 0.3588, 0.6119, 0.5522, 0.0527],
        [0.2363, 0.

tensor([-5.1902e-04, -4.0926e-04, -3.0583e-04, -2.4767e-04, -2.1417e-04,
        -1.9420e-04, -1.4445e-04, -1.2657e-04, -9.7100e-05, -9.3415e-05,
        -8.5308e-05, -6.7117e-05, -7.0590e-05, -1.4098e-05, -7.5794e-06,
        -5.1569e-06,  2.3477e-06,  6.3041e-06,  1.4036e-05, -5.2808e-05,
        -4.6499e-05, -4.5829e-05, -4.6036e-05,  1.6029e-05, -4.4977e-05,
        -3.3590e-05,  1.7605e-05, -2.3501e-05, -1.8886e-05,  1.6661e-05,
        -1.5843e-05, -1.5402e-05, -1.2630e-05,  1.5648e-05,  1.4427e-05,
        -9.6273e-06,  1.2408e-05, -7.3064e-06,  1.4795e-05,  1.3051e-05,
         1.2142e-05, -3.4374e-06,  8.8679e-06,  1.0384e-05,  1.1429e-05,
         3.1614e-07,  3.2004e-06,  6.3401e-06,  5.3660e-06,  6.6283e-06])
tensor([[0.5789, 0.3032, 0.3835, 0.0278, 0.0847],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5041, 0.5403, 0.0547, 0.2605, 0.6296],
        [0.5398, 0.0666, 0.2993, 0.0000, 0.2778],
        [0.5722, 0.0082, 0.0000, 0.0000, 0.1005],
        [0.4834, 0.

tensor([-1.1019e-04, -1.0975e-04, -1.0939e-04, -1.0878e-04, -9.8051e-05,
        -8.8250e-05, -8.3644e-05, -8.0853e-05, -8.0152e-05, -7.7520e-05,
        -7.4553e-05, -7.2253e-05, -6.8226e-05, -6.4523e-05, -6.3912e-05,
        -6.0638e-05, -5.7590e-05, -5.6201e-05, -5.6331e-05, -5.3455e-05,
        -5.0961e-05, -4.9639e-05, -4.8482e-05, -4.7640e-05, -4.7039e-05,
        -4.4265e-05, -4.3712e-05, -4.3397e-05, -4.2060e-05, -3.8548e-05,
        -3.6705e-05, -3.3107e-05, -2.9213e-05, -2.5122e-05, -2.0534e-05,
        -1.8621e-05, -1.6134e-05, -1.5104e-05,  1.3361e-06, -1.3215e-05,
         2.1782e-07, -2.2409e-08, -4.8275e-07, -6.4652e-06, -6.5823e-06,
        -4.2845e-06, -4.0306e-06, -5.1446e-06, -1.4693e-06, -2.3948e-06])
tensor([[0.2553, 0.4794, 0.0731, 0.3782, 0.0968],
        [0.2416, 0.3588, 0.6119, 0.5522, 0.0527],
        [0.2363, 0.4761, 0.2054, 0.6404, 0.6526],
        [0.2415, 0.8560, 0.0921, 0.8042, 0.4475],
        [0.2557, 0.6601, 0.4883, 0.7699, 0.4167],
        [0.2707, 0.

tensor([-3.5178e-05, -2.5420e-05, -1.6907e-05, -1.2858e-05, -1.0377e-05,
        -9.6502e-06, -7.3642e-06, -4.3717e-06, -2.3318e-06,  1.3194e-06,
         4.6247e-06,  5.2004e-06,  7.8424e-06,  1.0528e-05,  1.1902e-05,
         1.1800e-05,  1.4136e-05,  1.6204e-05,  1.7937e-05,  1.8785e-05,
         1.9028e-05,  1.9791e-05,  2.2652e-05,  2.2822e-05,  2.2961e-05,
         2.4278e-05,  2.7721e-05,  2.9051e-05,  3.2466e-05,  3.5535e-05,
         3.9105e-05,  4.3001e-05,  4.5302e-05,  4.7545e-05,  4.8223e-05,
         4.9831e-05,  5.5985e-05,  5.6268e-05,  5.6814e-05,  5.7047e-05,
         5.7436e-05,  5.9119e-05,  5.8868e-05,  6.0029e-05,  5.9814e-05,
         5.9559e-05,  5.9417e-05,  6.0189e-05,  5.8226e-05,  3.7121e-05])
tensor([[0.2415, 0.8560, 0.0921, 0.8042, 0.4475],
        [0.2557, 0.6601, 0.4883, 0.7699, 0.4167],
        [0.2707, 0.6536, 0.7160, 0.0000, 0.1673],
        [0.2622, 0.2320, 0.8679, 0.5884, 0.7208],
        [0.2718, 0.8298, 0.4835, 0.4183, 0.2267],
        [0.2976, 0.

tensor([-1.1354e-04, -1.1082e-04, -1.0996e-04, -1.0729e-04, -1.0418e-04,
        -1.0208e-04, -9.7887e-05, -9.3812e-05, -9.3248e-05, -9.0017e-05,
        -8.6955e-05, -8.5314e-05, -8.5454e-05, -8.2624e-05, -7.9988e-05,
        -7.8361e-05, -7.7218e-05, -7.6493e-05, -7.5917e-05, -7.2838e-05,
        -7.2424e-05, -7.2087e-05, -7.0565e-05, -6.6730e-05, -6.5031e-05,
        -6.1126e-05, -5.6754e-05, -5.2134e-05, -4.6859e-05, -4.4058e-05,
        -4.1165e-05, -3.9960e-05, -3.7494e-05,  7.9295e-06, -2.7300e-05,
        -2.7337e-05, -2.5125e-05, -2.3782e-05, -2.3738e-05, -2.0425e-05,
        -1.8446e-05, -1.5132e-05,  6.0627e-06, -1.5676e-05, -1.4608e-05,
        -1.1758e-05, -1.4870e-05, -1.3519e-05, -8.1158e-06,  1.2417e-06])
tensor([[0.2622, 0.2320, 0.8679, 0.5884, 0.7208],
        [0.2718, 0.8298, 0.4835, 0.4183, 0.2267],
        [0.2976, 0.3316, 0.4643, 0.1981, 0.2242],
        [0.2912, 0.5799, 0.1257, 0.5148, 0.2973],
        [0.2754, 0.1459, 0.4767, 0.7718, 0.8759],
        [0.3031, 0.

tensor([0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005,
        0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005,
        0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005,
        0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005,
        0.0005, 0.0004, 0.0003, 0.0002, 0.0002])
tensor([[0.6310, 0.6042, 0.4713, 0.4874, 0.7946],
        [0.6341, 0.4987, 0.5336, 0.3497, 0.7794],
        [0.6219, 0.4601, 0.3155, 0.4678, 0.7955],
        [0.5874, 0.4776, 0.3689, 0.3622, 0.8958],
        [0.2976, 0.3316, 0.4643, 0.1981, 0.2242],
        [0.2912, 0.5799, 0.1257, 0.5148, 0.2973],
        [0.2754, 0.1459, 0.4767, 0.7718, 0.8759],
        [0.3031, 0.0179, 0.3089, 0.3764, 0.6353],
        [0.3707, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3137, 0.4885, 0.0763, 0.1555, 0.5314],
        [0.2861, 0.3276, 0.7209, 1.0000, 0.7126],
 

tensor([ 1.4131e-04,  1.4078e-04,  1.3763e-04,  1.3690e-04,  1.2910e-04,
         1.2597e-04,  1.2467e-04,  1.2438e-04,  1.2386e-04,  1.2350e-04,
         1.2298e-04,  1.2243e-04,  1.2065e-04,  1.1849e-04,  1.1574e-04,
         1.1585e-04,  1.1486e-04,  1.1269e-04,  1.1245e-04,  1.0401e-04,
         1.0169e-04,  1.0040e-04,  9.8216e-05,  9.5686e-05,  9.1400e-05,
         8.7179e-05,  8.3177e-05,  7.9434e-05,  7.7780e-05,  7.4394e-05,
         7.2973e-05,  7.2722e-05,  7.2485e-05,  6.9507e-05,  6.9034e-05,
         6.8600e-05,  6.7523e-05,  6.5803e-05, -5.6440e-05,  6.3589e-05,
         6.0922e-05,  6.1240e-05,  5.9545e-05,  5.7019e-05,  5.3979e-05,
         5.4148e-05,  5.0091e-05,  4.6320e-05,  4.4430e-05,  4.1796e-05])
tensor([[0.2789, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2976, 0.3316, 0.4643, 0.1981, 0.2242],
        [0.2912, 0.5799, 0.1257, 0.5148, 0.2973],
        [0.2754, 0.1459, 0.4767, 0.7718, 0.8759],
        [0.3031, 0.0179, 0.3089, 0.3764, 0.6353],
        [0.3707, 0.

tensor([ 1.4787e-06,  6.7253e-06,  1.3057e-05,  1.3400e-05,  1.5030e-05,
         1.3636e-05,  1.3685e-05,  1.2693e-05,  1.4450e-05,  1.3710e-05,
         1.2064e-05,  1.3616e-05,  1.2551e-05,  1.2968e-05, -3.5498e-05,
        -3.3398e-05,  1.2112e-05, -3.1963e-05, -2.9484e-05, -2.7225e-05,
         1.1600e-05, -2.6521e-05,  1.0672e-05, -2.4178e-05,  1.0320e-05,
        -2.2280e-05, -2.1223e-05, -2.1366e-05,  8.7693e-06, -1.9869e-05,
         9.8581e-06, -1.7879e-05, -1.7237e-05, -1.6527e-05, -1.5810e-05,
        -1.5463e-05, -1.3751e-05, -1.3525e-05, -1.2953e-05, -1.2162e-05,
        -9.8754e-06, -8.9292e-06,  5.7796e-06,  4.4947e-06, -7.0304e-06,
         4.1698e-06, -4.0301e-06,  1.6157e-06, -1.7891e-06,  1.1491e-06])
tensor([[0.2912, 0.5799, 0.1257, 0.5148, 0.2973],
        [0.2754, 0.1459, 0.4767, 0.7718, 0.8759],
        [0.3031, 0.0179, 0.3089, 0.3764, 0.6353],
        [0.3707, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3137, 0.4885, 0.0763, 0.1555, 0.5314],
        [0.2861, 0.

tensor([ 5.3844e-05,  5.2265e-05,  4.5330e-05,  4.2659e-05,  4.1108e-05,
         3.8650e-05,  3.6945e-05,  3.5655e-05,  3.6296e-05,  3.5447e-05,
         3.6162e-05,  3.5208e-05,  3.4739e-05,  3.1953e-05,  3.0041e-05,
        -4.3118e-05, -4.1290e-05,  2.6801e-05,  2.6972e-05, -3.7792e-05,
         2.5462e-05, -3.4464e-05,  2.3372e-05, -3.3998e-05,  2.3415e-05,
        -3.1330e-05, -2.8707e-05, -2.7460e-05, -2.7530e-05, -2.4930e-05,
        -2.1629e-05, -2.2899e-05, -2.0551e-05,  1.4110e-05, -1.9880e-05,
        -1.9413e-05, -1.6901e-05,  1.1927e-05, -1.6362e-05, -1.4904e-05,
        -1.6112e-05,  1.0777e-05,  8.2290e-06, -1.1664e-05, -1.0028e-05,
         1.2967e-06,  3.8629e-06, -6.5492e-06,  5.8808e-06, -2.8466e-06])
tensor([[0.2754, 0.1459, 0.4767, 0.7718, 0.8759],
        [0.3031, 0.0179, 0.3089, 0.3764, 0.6353],
        [0.3707, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3137, 0.4885, 0.0763, 0.1555, 0.5314],
        [0.2861, 0.3276, 0.7209, 1.0000, 0.7126],
        [0.2938, 0.

tensor([ 0.0011,  0.0011,  0.0011,  0.0011,  0.0011,  0.0011,  0.0011,  0.0011,
         0.0011,  0.0011,  0.0011,  0.0011,  0.0011,  0.0011,  0.0011,  0.0011,
         0.0011,  0.0011,  0.0011,  0.0011,  0.0011,  0.0011,  0.0011,  0.0011,
         0.0011,  0.0011,  0.0011,  0.0011,  0.0011, -0.0005,  0.0011,  0.0011,
         0.0011,  0.0010,  0.0010,  0.0010,  0.0010,  0.0009,  0.0009,  0.0009,
         0.0009,  0.0009,  0.0009,  0.0009,  0.0008,  0.0008,  0.0007,  0.0007,
         0.0005,  0.0004])
tensor([[0.5981, 0.6894, 0.4725, 0.6169, 0.5889],
        [0.5689, 0.5809, 0.3705, 0.4129, 0.3419],
        [0.5460, 0.6900, 0.6308, 0.1678, 0.4821],
        [0.4977, 0.9313, 0.3020, 0.8534, 0.4246],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5130, 0.3379, 0.4468, 0.1744, 0.6506],
        [0.5041, 0.5403, 0.0547, 0.2605, 0.6296],
        [0.5398, 0.0666, 0.2993, 0.0000, 0.2778],
        [0.4859, 0.6399, 0.4193, 0.5240, 0.3424],
        [0.4797, 0.6132, 0.1729, 0.8334, 0.

tensor([ 1.2809e-05,  1.5873e-05,  1.6499e-05,  1.8357e-05,  1.8687e-05,
         1.8627e-05,  1.8426e-05,  1.8240e-05,  1.8010e-05,  1.7753e-05,
         1.7731e-05,  1.7955e-05,  1.7775e-05,  1.7696e-05,  1.6954e-05,
         1.6341e-05,  1.5070e-05,  1.5124e-05, -2.6251e-05, -2.6558e-05,
         1.4341e-05,  1.3542e-05, -2.4018e-05,  1.3670e-05, -2.2004e-05,
        -2.1153e-05, -2.1050e-05, -1.9020e-05, -1.7408e-05, -1.6540e-05,
        -1.5640e-05, -1.4677e-05, -1.5085e-05,  8.8594e-06, -1.2734e-05,
         7.5525e-06, -1.2372e-05, -1.1268e-05,  6.7435e-06, -1.2248e-05,
         5.2862e-06, -8.8945e-06, -8.8024e-07,  2.3430e-06, -7.4994e-06,
         3.6281e-06, -4.9828e-06,  6.0253e-07, -5.1680e-07, -2.5063e-06])
tensor([[0.3137, 0.4885, 0.0763, 0.1555, 0.5314],
        [0.2861, 0.3276, 0.7209, 1.0000, 0.7126],
        [0.2938, 0.6591, 0.5691, 0.5648, 0.9140],
        [0.3141, 0.8497, 0.1462, 0.3675, 0.2428],
        [0.2901, 0.6692, 0.5567, 0.9855, 0.8359],
        [0.3150, 0.

tensor([-6.7137e-05, -6.5124e-05, -6.4283e-05, -6.4259e-05, -6.2484e-05,
        -6.0942e-05, -6.0031e-05, -5.9243e-05, -5.8812e-05, -5.8391e-05,
        -5.6574e-05, -5.6158e-05, -5.5984e-05, -5.5110e-05, -5.2715e-05,
        -5.1543e-05, -4.9054e-05, -4.6325e-05, -4.4809e-05, -4.4230e-05,
        -4.3989e-05, -4.3407e-05, -4.1470e-05, -3.9985e-05, -3.8394e-05,
        -3.6517e-05, -3.5701e-05, -3.5621e-05, -3.4191e-05, -2.7715e-05,
        -2.7569e-05, -2.6250e-05, -2.5231e-05, -2.5238e-05, -2.3021e-05,
        -2.1766e-05, -1.9776e-05, -1.9449e-05, -1.9400e-05, -1.9175e-05,
        -1.8825e-05, -1.8764e-05, -1.8407e-05, -1.7172e-05, -1.5543e-05,
        -1.4498e-05, -1.3112e-05, -1.2791e-05, -8.5356e-06, -7.4983e-06])
tensor([[0.2938, 0.6591, 0.5691, 0.5648, 0.9140],
        [0.2901, 0.6692, 0.5567, 0.9855, 0.8359],
        [0.3141, 0.8497, 0.1462, 0.3675, 0.2428],
        [0.3150, 0.1745, 0.6520, 0.1545, 0.7861],
        [0.2934, 0.7124, 0.9831, 0.8634, 0.8906],
        [0.3255, 0.

tensor([-9.3068e-05, -9.3129e-05, -9.0745e-05, -8.8652e-05, -8.7575e-05,
        -8.6582e-05, -8.5898e-05, -8.5343e-05, -8.2872e-05, -8.2482e-05,
        -8.2249e-05, -8.0986e-05, -7.7825e-05, -7.6163e-05, -7.5984e-05,
        -7.2843e-05, -6.9281e-05, -6.7314e-05, -6.6499e-05, -6.6006e-05,
        -6.5267e-05, -6.2682e-05, -6.0807e-05, -5.8647e-05, -5.6044e-05,
        -5.4951e-05, -5.4898e-05, -5.2827e-05, -4.3905e-05, -4.4051e-05,
        -4.2021e-05, -4.0573e-05, -4.0541e-05, -3.7480e-05, -3.5712e-05,
        -3.2970e-05, -3.2580e-05, -3.2490e-05, -3.2188e-05, -3.1654e-05,
        -3.1590e-05, -3.1041e-05, -2.9333e-05, -2.7018e-05, -2.5426e-05,
        -2.3375e-05, -2.3026e-05, -1.6763e-05, -1.5273e-05, -3.8671e-06])
tensor([[0.2901, 0.6692, 0.5567, 0.9855, 0.8359],
        [0.3150, 0.1745, 0.6520, 0.1545, 0.7861],
        [0.2934, 0.7124, 0.9831, 0.8634, 0.8906],
        [0.3255, 0.6078, 0.0425, 0.7680, 0.0289],
        [0.3615, 0.3245, 0.1739, 0.2127, 0.1659],
        [0.3145, 0.

tensor([9.7703e-05, 1.1025e-04, 1.1525e-04, 1.1601e-04, 1.1696e-04, 1.1710e-04,
        1.1689e-04, 1.1675e-04, 1.1620e-04, 1.1545e-04, 1.1523e-04, 1.1505e-04,
        1.1489e-04, 1.1498e-04, 1.1473e-04, 1.1478e-04, 1.1317e-04, 1.1237e-04,
        1.1051e-04, 1.1042e-04, 1.0967e-04, 1.0848e-04, 1.0843e-04, 1.0170e-04,
        1.0020e-04, 1.0001e-04, 9.9050e-05, 9.7057e-05, 9.4974e-05, 9.3245e-05,
        9.0873e-05, 8.9261e-05, 8.9675e-05, 9.0045e-05, 8.7115e-05, 8.3737e-05,
        8.0821e-05, 8.0285e-05, 7.8756e-05, 7.4263e-05, 7.5502e-05, 7.4137e-05,
        7.3699e-05, 7.0955e-05, 6.9944e-05, 7.0373e-05, 6.8752e-05, 6.7338e-05,
        6.5357e-05, 6.2700e-05])
tensor([[0.2901, 0.6692, 0.5567, 0.9855, 0.8359],
        [0.3150, 0.1745, 0.6520, 0.1545, 0.7861],
        [0.2934, 0.7124, 0.9831, 0.8634, 0.8906],
        [0.3255, 0.6078, 0.0425, 0.7680, 0.0289],
        [0.3615, 0.3245, 0.1739, 0.2127, 0.1659],
        [0.3145, 0.5809, 0.9060, 0.4201, 0.5653],
        [0.3112, 0.4811, 0.

tensor([-4.1327e-05, -3.6841e-05, -2.4810e-05, -1.8967e-05, -1.6761e-05,
        -1.6379e-05, -1.3825e-05, -1.1257e-05, -7.8219e-06, -6.7347e-06,
        -8.1216e-06, -5.2601e-06, -6.7471e-06, -7.5518e-06, -7.0111e-06,
        -2.6359e-05, -2.4534e-05, -2.2738e-05, -3.2808e-06, -2.1597e-05,
        -2.0917e-05, -2.0378e-05, -2.0075e-05, -1.8048e-05, -1.7845e-05,
        -1.7560e-05, -1.6560e-05, -2.7740e-06, -1.4217e-05, -1.3370e-05,
        -1.3147e-05, -1.1157e-05, -1.3470e-06, -1.5239e-06, -8.4354e-06,
        -1.0143e-06, -7.7310e-06, -6.9189e-06, -7.0609e-06, -6.3282e-06,
        -9.5253e-07, -5.1280e-06, -1.1894e-06, -4.7949e-06, -4.4243e-06,
        -3.3941e-06, -2.0929e-06, -1.8575e-06, -1.8793e-06, -8.0404e-07])
tensor([[0.5460, 0.6900, 0.6308, 0.1678, 0.4821],
        [0.2901, 0.6692, 0.5567, 0.9855, 0.8359],
        [0.5488, 0.6961, 0.1551, 0.0000, 0.2771],
        [0.3150, 0.1745, 0.6520, 0.1545, 0.7861],
        [0.2934, 0.7124, 0.9831, 0.8634, 0.8906],
        [0.3255, 0.

tensor([-0.0009, -0.0008, -0.0008, -0.0008, -0.0007, -0.0007, -0.0007, -0.0006,
        -0.0006, -0.0006, -0.0006, -0.0006, -0.0006, -0.0006, -0.0006, -0.0006,
        -0.0005, -0.0005, -0.0005, -0.0005, -0.0005, -0.0005, -0.0004, -0.0004,
        -0.0004, -0.0004, -0.0004, -0.0004, -0.0003, -0.0003, -0.0003, -0.0003,
        -0.0003, -0.0003, -0.0003, -0.0003, -0.0003, -0.0002, -0.0002, -0.0002,
        -0.0002, -0.0002, -0.0002, -0.0002, -0.0002, -0.0002, -0.0002, -0.0002,
        -0.0002, -0.0002])
tensor([[0.5488, 0.6961, 0.1551, 0.0000, 0.2771],
        [0.4977, 0.9313, 0.3020, 0.8534, 0.4246],
        [0.5083, 0.3274, 0.3602, 1.0000, 0.3162],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5130, 0.3379, 0.4468, 0.1744, 0.6506],
        [0.5041, 0.5403, 0.0547, 0.2605, 0.6296],
        [0.5398, 0.0666, 0.2993, 0.0000, 0.2778],
        [0.4859, 0.6399, 0.4193, 0.5240, 0.3424],
        [0.4797, 0.6132, 0.1729, 0.8334, 0.0000],
        [0.4844, 0.3483, 0.4517, 0.3447, 0.

tensor([-7.2538e-05, -7.1030e-05, -7.0067e-05, -6.9263e-05, -6.8851e-05,
        -6.8377e-05, -6.6432e-05, -6.6079e-05, -6.5948e-05, -6.5018e-05,
        -6.2517e-05, -6.1282e-05, -6.1104e-05, -5.8693e-05, -5.6014e-05,
        -5.4325e-05, -5.3818e-05, -5.3497e-05, -5.2939e-05, -5.2096e-05,
        -5.0862e-05, -5.0050e-05, -4.9344e-05, -4.7675e-05, -4.5637e-05,
        -4.4825e-05, -4.4762e-05, -4.3245e-05, -3.9925e-05, -3.8149e-05,
        -3.6323e-05, -3.6136e-05, -3.4791e-05, -3.3674e-05, -3.3712e-05,
        -3.1216e-05, -2.9958e-05, -2.7669e-05, -2.7339e-05, -2.7327e-05,
        -2.7166e-05, -2.6658e-05, -2.6670e-05, -2.6269e-05, -2.4794e-05,
        -2.3064e-05, -2.1849e-05, -2.0335e-05, -1.9982e-05, -1.8594e-05])
tensor([[0.2934, 0.7124, 0.9831, 0.8634, 0.8906],
        [0.3255, 0.6078, 0.0425, 0.7680, 0.0289],
        [0.3615, 0.3245, 0.1739, 0.2127, 0.1659],
        [0.3145, 0.5809, 0.9060, 0.4201, 0.5653],
        [0.3112, 0.4811, 0.7586, 0.6776, 0.8383],
        [0.3497, 0.

tensor([-2.8330e-04, -2.6146e-04, -2.5957e-04, -2.3410e-04, -2.2006e-04,
        -1.9518e-04, -1.8209e-04, -1.7711e-04, -1.7972e-04, -1.6760e-04,
        -1.7139e-04, -1.7378e-04, -1.6553e-04, -1.6787e-04, -1.4754e-04,
        -1.3085e-04, -1.1149e-04, -1.1104e-04, -1.0224e-04, -8.7499e-05,
        -8.8009e-05, -7.6913e-05, -6.6187e-05, -4.5843e-05, -3.4928e-05,
        -3.5295e-05, -3.0664e-05, -1.9841e-05, -1.3542e-05, -1.0858e-05,
        -6.9974e-06, -2.1427e-06, -8.4172e-07,  2.1904e-06,  2.7771e-06,
         6.5178e-06,  9.9335e-06,  1.9186e-05,  2.5815e-05,  2.5404e-05,
         2.8203e-05,  3.2879e-05,  3.3950e-05,  3.5307e-05,  3.6714e-05,
         3.9150e-05,  3.8592e-05,  4.0828e-05,  4.2296e-05,  4.2866e-05])
tensor([[0.4977, 0.9313, 0.3020, 0.8534, 0.4246],
        [0.5083, 0.3274, 0.3602, 1.0000, 0.3162],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5130, 0.3379, 0.4468, 0.1744, 0.6506],
        [0.5041, 0.5403, 0.0547, 0.2605, 0.6296],
        [0.5398, 0.

tensor([-4.4600e-04,  1.4819e-04,  1.4937e-04,  1.4931e-04,  1.4848e-04,
         1.4837e-04,  1.4905e-04,  1.4833e-04,  1.4813e-04,  1.4776e-04,
         1.4678e-04,  1.4499e-04,  1.4651e-04,  1.4285e-04,  1.3802e-04,
         1.3585e-04,  1.3258e-04,  1.3139e-04,  1.3114e-04,  1.2909e-04,
         1.2471e-04, -1.4093e-04, -1.4760e-04,  1.2160e-04,  1.1875e-04,
        -1.2148e-04, -1.0413e-04,  1.1555e-04,  1.0440e-04,  1.0013e-04,
         9.2039e-05,  1.0136e-04, -7.8757e-05, -6.0230e-05, -5.7951e-05,
        -5.7433e-05, -4.9059e-05,  6.9541e-05, -2.0669e-05, -4.8976e-05,
        -4.4536e-05, -4.6464e-05,  5.6501e-05,  1.8345e-05, -4.4110e-05,
         4.1458e-05,  1.7029e-05,  3.0670e-05, -4.2859e-06,  4.6320e-05])
tensor([[0.4977, 0.9313, 0.3020, 0.8534, 0.4246],
        [0.5083, 0.3274, 0.3602, 1.0000, 0.3162],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5130, 0.3379, 0.4468, 0.1744, 0.6506],
        [0.5041, 0.5403, 0.0547, 0.2605, 0.6296],
        [0.5398, 0.

tensor([0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001,
        0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001,
        0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0002,
        0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002,
        0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002,
        0.0002, 0.0002, 0.0002, 0.0002, 0.0002])
tensor([[0.3255, 0.6078, 0.0425, 0.7680, 0.0289],
        [0.3615, 0.3245, 0.1739, 0.2127, 0.1659],
        [0.3145, 0.5809, 0.9060, 0.4201, 0.5653],
        [0.3112, 0.4811, 0.7586, 0.6776, 0.8383],
        [0.3497, 0.2427, 0.0652, 0.6071, 0.3428],
        [0.3425, 0.3785, 0.4293, 0.2386, 0.6140],
        [0.3164, 0.9299, 0.7552, 0.4245, 0.6864],
        [0.3365, 0.4584, 0.5179, 0.6149, 0.4808],
        [0.3368, 0.7702, 0.1699, 0.7635, 0.4614],
        [0.3326, 0.2704, 0.6852, 0.7046, 0.9171],
        [0.4151, 0.0154, 0.0000, 0.1113, 0.1090],
 

tensor([0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003,
        0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003,
        0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003,
        0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003,
        0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003,
        0.0003, 0.0003, 0.0003, 0.0003, 0.0003])
tensor([[0.3615, 0.3245, 0.1739, 0.2127, 0.1659],
        [0.3145, 0.5809, 0.9060, 0.4201, 0.5653],
        [0.3112, 0.4811, 0.7586, 0.6776, 0.8383],
        [0.3497, 0.2427, 0.0652, 0.6071, 0.3428],
        [0.3425, 0.3785, 0.4293, 0.2386, 0.6140],
        [0.3164, 0.9299, 0.7552, 0.4245, 0.6864],
        [0.3365, 0.4584, 0.5179, 0.6149, 0.4808],
        [0.3368, 0.7702, 0.1699, 0.7635, 0.4614],
        [0.5083, 0.3274, 0.3602, 1.0000, 0.3162],
        [0.3326, 0.2704, 0.6852, 0.7046, 0.9171],
        [0.4151, 0.0154, 0.0000, 0.1113, 0.1090],
 

tensor([ 2.4623e-05,  2.4196e-05,  2.3433e-05,  2.2542e-05,  2.2374e-05,
         2.0831e-05,  1.9709e-05,  1.9065e-05,  1.9118e-05,  1.8446e-05,
         1.8498e-05,  1.8511e-05,  1.8409e-05,  1.8225e-05,  1.6035e-05,
        -2.5580e-05,  1.4391e-05, -2.5149e-05,  1.4582e-05, -2.3138e-05,
        -2.2495e-05, -2.2653e-05, -2.1478e-05, -1.8843e-05,  1.2395e-05,
        -1.7344e-05,  1.2151e-05, -1.7245e-05,  1.1052e-05,  1.1194e-05,
        -1.4493e-05, -1.1639e-05,  9.4131e-06,  9.5653e-06, -9.8635e-06,
        -9.2864e-06, -8.7041e-06, -8.1630e-06,  7.4907e-06, -7.4361e-06,
        -6.0741e-06,  5.7422e-06, -5.0769e-06, -4.4180e-06, -2.6379e-06,
         2.0633e-06, -9.2983e-07,  4.0684e-07, -5.6095e-07,  4.1113e-07])
tensor([[0.3112, 0.4811, 0.7586, 0.6776, 0.8383],
        [0.3497, 0.2427, 0.0652, 0.6071, 0.3428],
        [0.3425, 0.3785, 0.4293, 0.2386, 0.6140],
        [0.3164, 0.9299, 0.7552, 0.4245, 0.6864],
        [0.3365, 0.4584, 0.5179, 0.6149, 0.4808],
        [0.3368, 0.

tensor([-5.8802e-05, -5.8618e-05, -5.8481e-05, -5.7712e-05, -5.5722e-05,
        -5.4840e-05, -5.4598e-05, -5.2767e-05, -5.0516e-05, -4.9275e-05,
        -4.8819e-05, -4.8648e-05, -4.8069e-05, -4.7442e-05, -4.6468e-05,
        -4.5850e-05, -4.5317e-05, -4.3832e-05, -4.2573e-05, -4.2203e-05,
        -4.1911e-05, -4.1549e-05, -4.1462e-05, -4.0160e-05, -3.7443e-05,
        -3.6006e-05, -3.4504e-05, -3.4467e-05, -3.3216e-05, -3.3205e-05,
        -3.2366e-05, -3.2391e-05, -3.0337e-05, -3.0273e-05, -2.9136e-05,
        -2.7403e-05, -2.7047e-05, -2.6901e-05, -2.6749e-05, -2.6663e-05,
        -2.6482e-05, -2.6337e-05, -2.6023e-05, -2.4813e-05, -2.3988e-05,
        -2.3343e-05, -2.3099e-05, -2.2217e-05, -2.1206e-05, -2.0697e-05])
tensor([[0.3425, 0.3785, 0.4293, 0.2386, 0.6140],
        [0.3164, 0.9299, 0.7552, 0.4245, 0.6864],
        [0.3365, 0.4584, 0.5179, 0.6149, 0.4808],
        [0.3368, 0.7702, 0.1699, 0.7635, 0.4614],
        [0.3326, 0.2704, 0.6852, 0.7046, 0.9171],
        [0.4151, 0.

tensor([-3.0474e-04, -2.1671e-04, -2.8150e-05, -2.6241e-05, -1.7647e-05,
        -1.6390e-05, -9.0839e-06, -9.0954e-06, -5.8355e-06, -1.0119e-06,
         1.1839e-06, -3.3174e-06, -1.8140e-07,  2.6031e-06,  3.0719e-06,
         2.0906e-06,  6.8324e-06,  9.7689e-06,  9.1642e-06,  1.1728e-05,
         1.7479e-05,  1.9520e-05,  1.9763e-05,  1.8366e-05,  2.1045e-05,
         2.0985e-05,  2.2154e-05,  2.4222e-05,  2.7722e-05,  2.7882e-05,
         2.9705e-05,  2.9306e-05,  2.8693e-05,  2.9783e-05,  3.0803e-05,
         3.2163e-05,  3.2603e-05,  3.1781e-05,  3.1429e-05,  3.2264e-05,
         3.1565e-05,  3.2007e-05,  3.3283e-05,  3.1213e-05,  3.2178e-05,
         3.0875e-05,  2.9675e-05,  3.1264e-05,  2.9352e-05,  2.9188e-05])
tensor([[0.6441, 0.4489, 0.2089, 0.6022, 0.6885],
        [0.5297, 0.7476, 0.0000, 0.3605, 0.0000],
        [0.5083, 0.3274, 0.3602, 1.0000, 0.3162],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5063, 0.7102, 0.0724, 0.5923, 0.2993],
        [0.5481, 0.

tensor([0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008,
        0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008,
        0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008,
        0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008,
        0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008, 0.0008,
        0.0008, 0.0007, 0.0007, 0.0004, 0.0002])
tensor([[0.7231, 0.5451, 0.3324, 0.6712, 0.6309],
        [0.6441, 0.4489, 0.2089, 0.6022, 0.6885],
        [0.5083, 0.3274, 0.3602, 1.0000, 0.3162],
        [0.5297, 0.7476, 0.0000, 0.3605, 0.0000],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5063, 0.7102, 0.0724, 0.5923, 0.2993],
        [0.5130, 0.3379, 0.4468, 0.1744, 0.6506],
        [0.5481, 0.3401, 0.0086, 0.0000, 0.3054],
        [0.5041, 0.5403, 0.0547, 0.2605, 0.6296],
        [0.5398, 0.0666, 0.2993, 0.0000, 0.2778],
        [0.4859, 0.6399, 0.4193, 0.5240, 0.3424],
 

tensor([0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0003, 0.0004, 0.0003, 0.0003,
        0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003,
        0.0003, 0.0003, 0.0002, 0.0001, 0.0001])
tensor([[0.7521, 0.5594, 0.4691, 0.4886, 0.6056],
        [0.7231, 0.5451, 0.3324, 0.6712, 0.6309],
        [0.6441, 0.4489, 0.2089, 0.6022, 0.6885],
        [0.5083, 0.3274, 0.3602, 1.0000, 0.3162],
        [0.5297, 0.7476, 0.0000, 0.3605, 0.0000],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5130, 0.3379, 0.4468, 0.1744, 0.6506],
        [0.5063, 0.7102, 0.0724, 0.5923, 0.2993],
        [0.5481, 0.3401, 0.0086, 0.0000, 0.3054],
        [0.5398, 0.0666, 0.2993, 0.0000, 0.2778],
        [0.5041, 0.5403, 0.0547, 0.2605, 0.6296],
 

tensor([-3.9149e-05, -3.8983e-05, -3.7538e-05, -3.7093e-05, -3.5410e-05,
        -3.4848e-05, -3.3525e-05, -3.3066e-05, -3.2878e-05, -3.2421e-05,
        -3.1726e-05, -3.0738e-05, -3.0127e-05, -2.9519e-05, -2.8201e-05,
        -2.6943e-05, -2.6572e-05, -2.6204e-05, -2.5943e-05, -2.5852e-05,
        -2.4721e-05, -2.4158e-05, -2.2036e-05,  4.4357e-06, -2.0652e-05,
        -1.9205e-05, -1.9081e-05, -1.7991e-05, -1.7903e-05, -1.7141e-05,
        -1.7134e-05, -1.5224e-05, -1.5230e-05, -1.4259e-05, -1.2537e-05,
        -1.2201e-05, -1.2196e-05, -1.1698e-05, -1.2129e-05, -1.2101e-05,
        -1.1374e-05, -1.1695e-05, -1.0243e-05, -9.5522e-06, -8.9448e-06,
        -8.8550e-06, -7.9590e-06, -7.2010e-06,  5.3936e-06, -6.9266e-06])
tensor([[0.4151, 0.0154, 0.0000, 0.1113, 0.1090],
        [0.3310, 0.8078, 0.4277, 0.7791, 1.0000],
        [0.3766, 0.0000, 0.3217, 0.2736, 0.5592],
        [0.3562, 0.8621, 0.3043, 0.2609, 0.6591],
        [0.3761, 0.5861, 0.3238, 0.4924, 0.1544],
        [0.4089, 0.

tensor([0.0027, 0.0027, 0.0026, 0.0026, 0.0026, 0.0026, 0.0026, 0.0026, 0.0026,
        0.0026, 0.0026, 0.0026, 0.0026, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025,
        0.0025, 0.0025, 0.0025, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024,
        0.0024, 0.0023, 0.0023, 0.0023, 0.0023, 0.0023, 0.0023, 0.0023, 0.0023,
        0.0023, 0.0022, 0.0022, 0.0022, 0.0022, 0.0022, 0.0022, 0.0022, 0.0022,
        0.0021, 0.0021, 0.0019, 0.0016, 0.0012])
tensor([[0.6755, 0.6343, 0.1994, 0.4597, 0.9705],
        [0.6441, 0.4489, 0.2089, 0.6022, 0.6885],
        [0.5860, 0.3069, 0.1567, 0.5640, 0.6146],
        [0.5083, 0.3274, 0.3602, 1.0000, 0.3162],
        [0.5297, 0.7476, 0.0000, 0.3605, 0.0000],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5130, 0.3379, 0.4468, 0.1744, 0.6506],
        [0.5063, 0.7102, 0.0724, 0.5923, 0.2993],
        [0.5481, 0.3401, 0.0086, 0.0000, 0.3054],
        [0.5041, 0.5403, 0.0547, 0.2605, 0.6296],
        [0.5398, 0.0666, 0.2993, 0.0000, 0.2778],
 

tensor([ 1.8277e-05, -7.2219e-05, -5.6271e-05, -2.8574e-05, -2.6956e-05,
        -2.6240e-05, -2.4038e-05, -2.3143e-05, -2.1457e-05, -2.0939e-05,
         1.1768e-05, -2.0739e-05, -1.9976e-05, -1.9101e-05,  1.1654e-05,
        -1.7929e-05, -1.7138e-05, -1.6411e-05,  1.0389e-05, -1.4340e-05,
        -1.2933e-05,  9.7223e-06, -1.2327e-05, -1.1945e-05, -1.1293e-05,
        -1.1592e-05,  9.3146e-06,  8.8254e-06, -9.8450e-06, -9.2788e-06,
         7.9561e-06, -6.3672e-06,  6.2832e-06,  6.6454e-06, -4.6846e-06,
         6.0666e-06,  5.9588e-06,  6.0610e-06,  5.7980e-06, -2.8082e-06,
         5.5493e-06, -2.8446e-06,  5.1125e-06, -1.3038e-06, -1.3001e-06,
         2.0598e-06, -5.2786e-07,  3.1710e-06,  1.9244e-06, -4.3793e-07])
tensor([[0.2695, 0.6474, 0.6186, 0.5937, 0.7874],
        [0.4151, 0.0154, 0.0000, 0.1113, 0.1090],
        [0.3310, 0.8078, 0.4277, 0.7791, 1.0000],
        [0.3766, 0.0000, 0.3217, 0.2736, 0.5592],
        [0.3562, 0.8621, 0.3043, 0.2609, 0.6591],
        [0.3761, 0.

tensor([-2.0200e-03, -5.7469e-04, -3.2254e-04, -3.1446e-04, -2.8660e-04,
        -2.6871e-04, -2.6673e-04, -2.5287e-04, -2.3361e-04, -2.1828e-04,
        -2.1028e-04, -2.0402e-04, -2.0065e-04, -2.0258e-04, -2.0252e-04,
        -1.9358e-04, -1.8574e-04, -1.6656e-04, -1.4653e-04, -1.4453e-04,
        -1.2362e-04, -1.2182e-04, -1.1829e-04, -1.0973e-04, -1.1243e-04,
        -9.3205e-05, -9.7979e-05, -7.9823e-05, -7.0204e-05, -4.7666e-05,
        -4.6936e-05, -4.2887e-07, -3.4282e-05, -1.7553e-06, -3.7928e-05,
        -1.0417e-06, -3.8881e-05, -3.3417e-05, -3.2592e-05, -4.6165e-06,
        -6.7294e-06, -8.2204e-06, -2.7822e-05, -1.2643e-05, -1.0150e-05,
        -1.7710e-05, -1.0322e-05, -1.3680e-05, -2.0350e-05, -1.6195e-05])
tensor([[0.5860, 0.3069, 0.1567, 0.5640, 0.6146],
        [0.5083, 0.3274, 0.3602, 1.0000, 0.3162],
        [0.5297, 0.7476, 0.0000, 0.3605, 0.0000],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5063, 0.7102, 0.0724, 0.5923, 0.2993],
        [0.5130, 0.

tensor([-6.4847e-05,  2.3765e-05,  2.4227e-05,  2.4063e-05,  2.4256e-05,
         2.4354e-05,  2.4248e-05,  2.3715e-05,  2.4030e-05,  2.3607e-05,
         2.3479e-05,  2.3215e-05,  2.3518e-05,  2.3359e-05,  2.3398e-05,
         2.3410e-05,  2.2160e-05,  2.1893e-05,  2.0605e-05,  2.2171e-05,
         2.0438e-05,  2.0238e-05, -1.3530e-05,  1.9506e-05,  2.0867e-05,
         2.0358e-05,  1.9328e-05,  1.8152e-05,  1.7100e-05,  1.2032e-05,
         1.5116e-06,  3.2629e-06,  1.4884e-05,  1.3819e-05,  9.9431e-06,
         7.2341e-06,  7.8691e-06,  9.3910e-06,  1.4074e-05,  2.6580e-06,
         1.0478e-05,  1.2786e-05,  1.3294e-05,  6.9259e-06,  1.5385e-05,
         8.5403e-06,  1.3646e-05,  4.8961e-06,  5.5103e-06,  7.1762e-06])
tensor([[0.2992, 0.2947, 0.6184, 0.6252, 0.5494],
        [0.3222, 1.0000, 0.0000, 0.6288, 1.0000],
        [0.4151, 0.0154, 0.0000, 0.1113, 0.1090],
        [0.3310, 0.8078, 0.4277, 0.7791, 1.0000],
        [0.3766, 0.0000, 0.3217, 0.2736, 0.5592],
        [0.3562, 0.

tensor([ 1.3573e-04,  1.3712e-04,  1.3810e-04,  1.3974e-04,  1.4029e-04,
         1.4195e-04,  1.4201e-04,  1.4278e-04,  1.4314e-04,  1.4355e-04,
         1.4449e-04,  1.4523e-04,  1.4575e-04,  1.4694e-04,  1.4768e-04,
         1.4799e-04,  1.4846e-04,  1.4862e-04,  1.4879e-04,  1.4937e-04,
         1.4969e-04,  1.5114e-04,  1.5173e-04,  1.5251e-04,  1.5248e-04,
         1.5302e-04,  1.5302e-04,  1.5381e-04,  1.5295e-04,  1.5300e-04,
         1.5333e-04,  1.5327e-04,  1.5360e-04,  1.5366e-04,  1.5307e-04,
         1.5324e-04,  1.5303e-04,  1.5260e-04,  1.5318e-04,  1.5280e-04,
         1.5355e-04,  1.5248e-04,  1.5230e-04,  1.5230e-04,  1.5145e-04,
         1.5075e-04,  1.5046e-04,  1.4957e-04,  1.1293e-04, -5.2782e-05])
tensor([[0.7702, 0.3480, 0.3000, 0.4511, 1.0000],
        [0.6469, 0.0000, 0.1809, 0.0000, 1.0000],
        [0.4151, 0.0154, 0.0000, 0.1113, 0.1090],
        [0.3310, 0.8078, 0.4277, 0.7791, 1.0000],
        [0.3766, 0.0000, 0.3217, 0.2736, 0.5592],
        [0.3562, 0.

tensor([-1.8941e-04, -9.0673e-05, -1.4569e-05, -1.5067e-05, -1.3158e-05,
        -1.1371e-05, -1.0667e-05, -1.0396e-05, -9.0915e-06, -6.6434e-06,
        -6.4132e-06, -4.9508e-06, -4.8448e-06, -5.8615e-06, -5.6515e-06,
        -5.9402e-06, -5.2009e-06, -4.0447e-06, -1.7503e-06, -1.0980e-06,
        -1.6273e-06,  7.7362e-07,  9.3203e-07,  1.0619e-06,  1.5121e-06,
         1.3320e-06,  1.5783e-06,  1.8404e-06,  7.9642e-07,  3.8271e-07,
         3.7420e-06,  4.1278e-06,  2.9579e-06,  1.8313e-06,  2.6684e-06,
         3.4856e-06,  3.4514e-06,  3.7392e-06,  2.5908e-06,  3.7923e-06,
         4.9999e-06,  3.8152e-06,  3.6649e-06,  4.8627e-06,  4.5671e-06,
         3.8613e-06,  4.3595e-06,  4.3401e-06,  4.7825e-06,  4.0422e-06])
tensor([[0.6469, 0.0000, 0.1809, 0.0000, 1.0000],
        [0.5297, 0.7476, 0.0000, 0.3605, 0.0000],
        [0.5083, 0.3274, 0.3602, 1.0000, 0.3162],
        [0.4827, 0.6893, 0.4868, 0.8115, 0.8544],
        [0.5130, 0.3379, 0.4468, 0.1744, 0.6506],
        [0.5063, 0.

tensor([ 3.9763e-05,  2.4706e-05,  2.4150e-05,  2.3176e-05,  2.2100e-05,
         2.1946e-05,  2.1122e-05,  2.0246e-05,  1.8863e-05,  1.8423e-05,
         1.8486e-05,  1.7953e-05,  1.7809e-05,  1.7766e-05,  1.8052e-05,
         1.7406e-05,  1.7437e-05,  1.5271e-05,  1.3794e-05,  1.3953e-05,
         1.1837e-05,  1.1544e-05,  1.0533e-05,  1.0487e-05,  1.1556e-05,
        -1.3762e-05, -1.3132e-05,  9.0679e-06,  8.9468e-06, -1.1168e-05,
        -1.0412e-05, -8.8578e-06,  7.1674e-06, -8.2738e-06,  5.4615e-06,
        -6.6233e-06, -7.3732e-06, -7.9657e-06, -5.4086e-06,  9.8611e-08,
        -3.9174e-06,  2.6715e-06, -2.2442e-06, -4.6032e-06,  6.1617e-07,
         2.1326e-06,  8.8949e-07,  5.3463e-07, -2.7409e-07, -6.9876e-07])
tensor([[0.3766, 0.0000, 0.3217, 0.2736, 0.5592],
        [0.3562, 0.8621, 0.3043, 0.2609, 0.6591],
        [0.3761, 0.5861, 0.3238, 0.4924, 0.1544],
        [0.4089, 0.3865, 0.0000, 0.0000, 0.2830],
        [0.3586, 0.9147, 0.4889, 0.6223, 0.4957],
        [0.3623, 0.

tensor([-5.5058e-05, -5.4275e-05, -5.2849e-05, -5.2001e-05, -5.2229e-05,
        -5.1410e-05, -5.0652e-05, -4.9470e-05, -4.8717e-05, -4.8051e-05,
        -4.6454e-05, -4.4874e-05, -4.4270e-05, -4.4480e-05, -4.4136e-05,
        -4.3695e-05, -4.3629e-05, -4.3348e-05, -4.2122e-05, -4.1617e-05,
        -3.8863e-05, -3.7490e-05, -3.7182e-05, -3.5490e-05, -3.5358e-05,
        -3.3950e-05, -3.3894e-05, -3.2909e-05, -3.2884e-05, -3.2584e-05,
        -3.0494e-05, -3.0642e-05, -2.9179e-05, -2.7079e-05, -2.7062e-05,
        -2.6637e-05, -2.6685e-05, -2.6484e-05, -2.6332e-05, -2.6013e-05,
        -2.5919e-05, -2.5569e-05, -2.4150e-05, -2.3232e-05, -2.2390e-05,
        -2.2239e-05, -2.1116e-05, -1.9489e-05, -2.0086e-05, -5.1308e-08])
tensor([[0.3761, 0.5861, 0.3238, 0.4924, 0.1544],
        [0.4089, 0.3865, 0.0000, 0.0000, 0.2830],
        [0.3586, 0.9147, 0.4889, 0.6223, 0.4957],
        [0.3623, 0.1806, 0.8263, 0.3941, 0.8267],
        [0.4075, 0.0943, 0.4056, 0.3135, 0.2006],
        [0.4022, 0.

tensor([-3.8439e-05, -3.8018e-05, -3.7873e-05, -3.7376e-05, -3.6853e-05,
        -3.6023e-05, -3.5482e-05, -3.5009e-05, -3.3773e-05, -3.2668e-05,
        -3.2372e-05, -3.2283e-05, -3.2110e-05, -3.1826e-05, -3.1725e-05,
        -3.1526e-05, -3.0651e-05, -3.0322e-05, -2.8336e-05, -2.7373e-05,
        -2.7169e-05, -2.6899e-05, -2.5977e-05, -2.5959e-05, -2.4900e-05,
        -2.4880e-05, -2.4206e-05, -2.4203e-05, -2.3961e-05, -2.2560e-05,
        -2.2527e-05, -2.1580e-05, -2.0289e-05, -2.0204e-05, -1.9992e-05,
        -1.9871e-05, -1.9746e-05, -1.9658e-05, -1.9528e-05, -1.9381e-05,
        -1.9151e-05, -1.8254e-05, -1.7577e-05, -1.7063e-05, -1.6878e-05,
        -1.6221e-05, -1.5413e-05, -1.5063e-05, -3.9032e-06, -3.5599e-06])
tensor([[0.3586, 0.9147, 0.4889, 0.6223, 0.4957],
        [0.3623, 0.1806, 0.8263, 0.3941, 0.8267],
        [0.4075, 0.0943, 0.4056, 0.3135, 0.2006],
        [0.4022, 0.4311, 0.1442, 0.3645, 0.3146],
        [0.3920, 0.2803, 0.3155, 0.5413, 0.5360],
        [0.3786, 0.

tensor([-3.9099e-05, -3.8701e-05, -3.8255e-05, -3.7510e-05, -3.7041e-05,
        -3.6650e-05, -3.5620e-05, -3.4633e-05, -3.4398e-05, -3.4278e-05,
        -3.4178e-05, -3.3902e-05, -3.3861e-05, -3.3671e-05, -3.2897e-05,
        -3.2624e-05, -3.0896e-05, -3.0045e-05, -2.9851e-05, -2.9546e-05,
        -2.8790e-05, -2.8732e-05, -2.7842e-05, -2.7816e-05, -2.7199e-05,
        -2.7168e-05, -2.7005e-05, -2.5766e-05, -2.5695e-05, -2.4859e-05,
        -2.3617e-05, -2.3564e-05, -2.3368e-05, -2.3309e-05, -2.3207e-05,
        -2.3150e-05, -2.2944e-05, -2.2880e-05, -2.2646e-05, -2.1807e-05,
        -2.1219e-05, -2.0712e-05, -2.0633e-05, -1.9920e-05, -1.9292e-05,
        -1.8900e-05, -1.5089e-05, -7.4767e-06, -7.4599e-06, -2.4281e-06])
tensor([[0.4075, 0.0943, 0.4056, 0.3135, 0.2006],
        [0.4022, 0.4311, 0.1442, 0.3645, 0.3146],
        [0.3920, 0.2803, 0.3155, 0.5413, 0.5360],
        [0.3786, 0.1227, 0.5651, 0.6127, 0.7860],
        [0.3836, 0.5029, 0.5009, 0.3544, 0.7642],
        [0.4844, 0.

tensor([-1.4518e-05, -1.3892e-05, -1.3396e-05, -1.2146e-05, -1.0950e-05,
        -1.0518e-05, -1.0771e-05, -1.0420e-05, -1.0079e-05, -1.0075e-05,
        -9.8570e-06, -8.9176e-06, -8.5606e-06, -6.7298e-06, -5.6708e-06,
        -5.5975e-06, -5.1801e-06, -4.3326e-06, -4.3288e-06, -3.4063e-06,
        -3.3668e-06, -2.6845e-06, -2.8017e-06, -2.6322e-06, -1.3159e-06,
        -1.3991e-06, -5.8097e-07,  5.7965e-07,  6.6624e-07,  8.0595e-07,
         9.3346e-07,  8.9551e-07,  1.2326e-06,  8.7949e-07,  1.2160e-06,
         1.4507e-06,  2.1119e-06,  2.6612e-06,  3.0547e-06,  2.9732e-06,
         3.6666e-06,  4.0027e-06,  4.3635e-06,  6.6099e-06,  8.7205e-06,
         8.4553e-06,  4.6207e-06, -2.0387e-05, -1.0040e-05, -1.0829e-05])
tensor([[0.3920, 0.2803, 0.3155, 0.5413, 0.5360],
        [0.3786, 0.1227, 0.5651, 0.6127, 0.7860],
        [0.3836, 0.5029, 0.5009, 0.3544, 0.7642],
        [0.4844, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3959, 0.5200, 0.4658, 0.7247, 0.4281],
        [0.7716, 0.

tensor([-1.3255e-05, -1.2776e-05, -1.1735e-05, -1.0890e-05, -1.0580e-05,
        -1.0564e-05, -1.0289e-05, -1.0143e-05, -1.0025e-05, -9.9480e-06,
        -9.2304e-06, -8.8451e-06, -7.2863e-06, -6.3766e-06, -6.3015e-06,
        -6.0201e-06, -5.2637e-06, -5.1903e-06, -4.3838e-06, -4.2892e-06,
        -4.1318e-06, -3.8815e-06, -3.8561e-06, -3.6269e-06, -2.4709e-06,
        -2.3980e-06, -1.7947e-06, -5.9242e-07, -6.9685e-07, -3.1080e-07,
        -2.6550e-07, -1.8702e-07, -1.4095e-07,  3.7190e-09,  7.5915e-08,
         2.6379e-07,  1.1251e-06,  1.6521e-06,  1.9902e-06,  2.1341e-06,
         2.6076e-06,  3.3084e-06,  3.4127e-06,  6.5981e-06,  1.1555e-05,
         1.1817e-05,  1.2051e-05,  1.2316e-05,  1.1913e-05,  9.5409e-06])
tensor([[0.3836, 0.5029, 0.5009, 0.3544, 0.7642],
        [0.4844, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3959, 0.5200, 0.4658, 0.7247, 0.4281],
        [0.4002, 0.6772, 0.0914, 0.6985, 0.3797],
        [0.4011, 0.1043, 0.6338, 0.2964, 0.7720],
        [0.3940, 1.

tensor([ 1.1974e-04,  1.2007e-04,  1.2018e-04,  1.2036e-04,  1.2061e-04,
         1.2071e-04,  1.2084e-04,  1.2155e-04,  1.2181e-04,  1.2338e-04,
         1.2415e-04,  1.2424e-04,  1.2448e-04,  1.2544e-04,  1.2527e-04,
         1.2598e-04,  1.2590e-04,  1.2610e-04,  1.2627e-04,  1.2642e-04,
         1.2645e-04,  1.2727e-04,  1.2739e-04,  1.2775e-04,  1.2842e-04,
         1.2840e-04,  1.2841e-04,  1.2881e-04,  1.2866e-04,  1.2842e-04,
         1.2858e-04,  1.2840e-04,  1.2887e-04,  1.2897e-04,  1.2912e-04,
         1.2893e-04,  1.2886e-04,  1.2870e-04,  1.2855e-04,  1.2848e-04,
         1.2483e-04, -2.0447e-04, -1.8591e-04,  9.6320e-05,  9.3770e-05,
         8.9339e-05,  6.0669e-05, -5.1947e-05,  3.1590e-05, -1.7944e-06])
tensor([[0.8434, 0.6761, 0.3958, 0.6123, 0.9632],
        [0.7734, 0.6049, 0.3308, 0.5838, 0.8642],
        [0.7407, 0.6918, 0.2111, 0.4543, 0.8197],
        [0.7236, 0.6363, 0.3522, 0.6055, 1.0000],
        [0.7134, 0.4117, 0.3707, 0.6472, 0.7746],
        [0.6933, 0.

tensor([ 2.9206e-05,  2.6300e-05,  2.3662e-05,  2.3556e-05,  2.1484e-05,
         1.9001e-05,  1.5805e-05,  1.4941e-05,  1.4921e-05, -1.3323e-05,
        -1.3524e-05, -1.3277e-05, -1.2906e-05, -1.2985e-05, -1.2729e-05,
        -1.2009e-05, -1.1742e-05, -9.9309e-06, -9.1619e-06, -8.9586e-06,
        -8.7274e-06, -7.7954e-06, -7.8256e-06, -6.8373e-06, -6.8289e-06,
         6.3308e-06, -6.1671e-06, -6.0555e-06, -6.2664e-06, -6.6039e-06,
        -4.7705e-06, -4.7666e-06, -3.8553e-06, -2.5185e-06, -2.2152e-06,
        -1.5187e-06, -2.1736e-06,  1.9165e-06, -2.5858e-06, -2.1568e-06,
        -1.8521e-06,  2.2272e-06,  4.4622e-07, -1.9076e-06, -2.3718e-06,
        -8.7452e-08,  1.0338e-06,  4.6244e-07, -7.4368e-07,  1.1456e-06])
tensor([[0.4011, 0.1043, 0.6338, 0.2964, 0.7720],
        [0.3940, 1.0000, 0.0000, 0.1586, 0.6257],
        [0.4355, 0.2667, 0.2067, 0.3766, 0.3054],
        [0.4403, 0.4836, 0.0000, 0.2398, 0.0000],
        [0.4411, 0.1783, 0.2762, 0.4310, 0.0000],
        [0.4258, 0.

tensor([-6.2226e-06,  5.2292e-06,  6.5172e-06, -2.3686e-05, -2.3437e-05,
        -2.3396e-05, -2.3221e-05, -2.2521e-05, -2.2248e-05, -2.0651e-05,
        -1.9853e-05, -1.9701e-05, -1.9433e-05, -1.8630e-05, -1.8645e-05,
         6.1790e-06, -1.7788e-05, -1.7777e-05, -1.7489e-05,  6.1322e-06,
        -1.7212e-05, -1.7153e-05, -1.7038e-05, -1.5820e-05, -1.5893e-05,
        -1.5037e-05, -1.3863e-05, -1.3795e-05, -1.3656e-05, -1.3551e-05,
        -1.3486e-05, -1.3458e-05, -1.3268e-05, -1.3214e-05, -1.2932e-05,
        -1.2183e-05, -1.1625e-05, -1.1500e-05, -1.1174e-05, -1.1101e-05,
        -1.0622e-05, -1.0499e-05, -9.8632e-06, -9.5389e-06, -5.9836e-06,
         5.2681e-06,  3.8755e-06,  1.0468e-06,  1.0513e-06,  1.7363e-06])
tensor([[0.4355, 0.2667, 0.2067, 0.3766, 0.3054],
        [0.4403, 0.4836, 0.0000, 0.2398, 0.0000],
        [0.4411, 0.1783, 0.2762, 0.4310, 0.0000],
        [0.4258, 0.2211, 0.2783, 0.7080, 0.0939],
        [0.4046, 0.9551, 0.1543, 0.4483, 0.4858],
        [0.4421, 0.

tensor([ 2.0817e-05,  1.7040e-05,  1.4759e-05,  1.4417e-05,  1.2741e-05,
         1.2664e-05,  1.1098e-05,  9.2415e-06,  6.9161e-06,  6.2202e-06,
         6.2854e-06,  5.2683e-06, -1.2889e-05, -1.2777e-05, -1.2284e-05,
        -1.2088e-05, -1.0950e-05, -1.0387e-05, -1.0273e-05, -1.0081e-05,
        -9.5222e-06, -9.5464e-06, -8.9086e-06, -8.8903e-06, -8.6823e-06,
        -8.4814e-06, -8.4755e-06, -8.3547e-06, -7.4790e-06, -7.4989e-06,
        -6.8928e-06, -6.0265e-06, -5.9901e-06, -5.8595e-06, -5.8002e-06,
        -5.7457e-06, -5.7074e-06, -5.5633e-06, -5.5138e-06, -5.3399e-06,
        -4.7515e-06, -4.3256e-06, -4.2171e-06, -3.9750e-06, -3.9129e-06,
        -3.5581e-06, -3.4377e-06, -2.9403e-06, -2.6996e-06,  1.3809e-07])
tensor([[0.4411, 0.1783, 0.2762, 0.4310, 0.0000],
        [0.4258, 0.2211, 0.2783, 0.7080, 0.0939],
        [0.4046, 0.9551, 0.1543, 0.4483, 0.4858],
        [0.4421, 0.4772, 0.4697, 0.3639, 0.0000],
        [0.4267, 0.9305, 0.0000, 0.2937, 0.4693],
        [0.4360, 0.

tensor([ 4.4185e-06,  4.2025e-06, -3.3796e-05, -3.2980e-05, -3.2679e-05,
         3.9899e-06, -3.0694e-05, -2.9823e-05, -2.9589e-05, -2.9285e-05,
        -2.8324e-05, -2.8337e-05, -2.7288e-05, -2.7291e-05, -2.6967e-05,
        -2.6579e-05, -2.6629e-05, -2.6426e-05, -2.4991e-05, -2.5082e-05,
        -2.4053e-05, -2.2689e-05, -2.2628e-05, -2.2435e-05, -2.2289e-05,
        -2.2219e-05, -2.2183e-05, -2.1958e-05, -2.1883e-05, -2.1563e-05,
        -2.0700e-05, -2.0026e-05, -1.9860e-05, -1.9478e-05, -1.9412e-05,
        -1.8817e-05, -1.8666e-05, -1.7927e-05, -1.7551e-05, -1.6926e-05,
        -1.3500e-05, -1.3310e-05,  2.6916e-06,  2.6310e-06, -6.0956e-06,
        -4.8693e-06, -4.7811e-06, -3.9648e-06,  1.0592e-06, -1.0656e-06])
tensor([[0.4258, 0.2211, 0.2783, 0.7080, 0.0939],
        [0.4046, 0.9551, 0.1543, 0.4483, 0.4858],
        [0.4421, 0.4772, 0.4697, 0.3639, 0.0000],
        [0.4267, 0.9305, 0.0000, 0.2937, 0.4693],
        [0.4360, 0.6397, 0.3477, 0.5841, 0.1752],
        [0.4005, 0.

tensor([ 1.6606e-05,  1.6796e-05,  1.6874e-05,  1.6667e-05,  1.5864e-05,
         1.5863e-05,  1.4589e-05,  1.3631e-05,  1.2674e-05,  9.7356e-06,
         8.7702e-06,  8.9423e-06,  7.2942e-06, -2.5765e-05, -2.1999e-05,
        -2.3234e-05, -2.1310e-05, -2.1733e-05, -2.0104e-05, -1.8752e-05,
        -2.0242e-05, -1.8819e-05, -1.8269e-05, -1.7867e-05, -1.7852e-05,
        -1.7597e-05, -1.5852e-05, -1.5771e-05, -1.2700e-05, -1.2389e-05,
        -1.2671e-05, -1.4534e-05, -1.1771e-05, -1.0184e-05, -1.2383e-05,
        -1.1415e-05, -1.1686e-05, -9.4063e-06, -1.2261e-05, -8.6277e-06,
        -1.2641e-06, -9.6817e-07, -1.2082e-05, -9.1159e-06, -7.5727e-06,
        -8.5065e-06, -7.8640e-06, -6.6521e-06, -6.2108e-06, -5.5202e-06])
tensor([[0.4421, 0.4772, 0.4697, 0.3639, 0.0000],
        [0.4267, 0.9305, 0.0000, 0.2937, 0.4693],
        [0.4360, 0.6397, 0.3477, 0.5841, 0.1752],
        [0.4005, 0.8885, 0.3525, 1.0000, 1.0000],
        [0.5371, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4550, 0.

tensor([-8.2255e-04, -7.9289e-04, -7.0126e-04, -6.4469e-04, -6.2223e-04,
        -5.1187e-04, -5.1601e-04, -4.3012e-04, -3.8329e-04, -3.4082e-04,
        -2.5089e-04, -2.2630e-04, -2.2882e-04, -1.9746e-04, -8.6450e-05,
        -7.5236e-05, -7.1070e-05, -3.6136e-05, -3.9863e-05, -2.5527e-05,
        -2.6962e-05, -2.1207e-05, -3.1574e-05, -2.0341e-05, -7.3592e-06,
        -7.2546e-06, -1.7894e-05, -2.2431e-05, -9.6621e-06, -1.0587e-05,
        -1.5141e-05,  1.3742e-06, -7.8106e-06, -9.3263e-06, -2.7641e-06,
        -7.8495e-06, -4.0598e-07,  1.7614e-07, -3.4647e-06, -1.6849e-06,
         1.4467e-07, -2.8338e-06, -6.0758e-07, -9.2327e-06,  1.1440e-06,
         1.2929e-06, -3.7926e-06,  6.4697e-07, -1.0027e-05, -3.1032e-07])
tensor([[0.8025, 0.6010, 0.2896, 0.6524, 1.0000],
        [0.7790, 0.7120, 0.3009, 0.7243, 0.8625],
        [0.7734, 0.6049, 0.3308, 0.5838, 0.8642],
        [0.7552, 0.6083, 0.1848, 0.7343, 1.0000],
        [0.7407, 0.6918, 0.2111, 0.4543, 0.8197],
        [0.7236, 0.

tensor([-1.4962e-05, -1.4846e-05, -1.3518e-05, -1.3260e-05, -1.2088e-05,
        -1.2045e-05, -1.2248e-05, -1.2237e-05, -1.1726e-05, -1.1219e-05,
        -1.1264e-05, -9.8676e-06, -9.7198e-06, -8.8937e-06, -7.2898e-06,
        -7.4073e-06, -7.2535e-06, -6.8129e-06, -6.8929e-06, -7.0373e-06,
        -6.6760e-06, -6.5881e-06, -6.0030e-06, -5.4656e-06, -4.9218e-06,
        -4.6781e-06, -4.1594e-06, -4.3288e-06, -3.7992e-06, -3.8514e-06,
        -2.5525e-05, -2.9075e-06, -2.9971e-06, -2.1420e-06, -1.9275e-05,
         2.2612e-07,  2.5082e-07,  6.5250e-07, -1.5584e-05, -1.4413e-05,
        -1.0180e-05, -8.1800e-06, -8.2370e-06,  2.1132e-06, -4.0653e-06,
         1.7765e-06,  1.8199e-06,  1.3234e-06, -2.4315e-06, -8.5039e-07])
tensor([[0.7790, 0.7120, 0.3009, 0.7243, 0.8625],
        [0.7734, 0.6049, 0.3308, 0.5838, 0.8642],
        [0.4360, 0.6397, 0.3477, 0.5841, 0.1752],
        [0.4005, 0.8885, 0.3525, 1.0000, 1.0000],
        [0.7552, 0.6083, 0.1848, 0.7343, 1.0000],
        [0.4550, 0.

tensor([-0.0012, -0.0011, -0.0011, -0.0010, -0.0010, -0.0010, -0.0009, -0.0008,
        -0.0008, -0.0007, -0.0007, -0.0006, -0.0006, -0.0006, -0.0006, -0.0004,
        -0.0004, -0.0004, -0.0004, -0.0003, -0.0004, -0.0003, -0.0003, -0.0003,
        -0.0003, -0.0003, -0.0003, -0.0003, -0.0003, -0.0003, -0.0003, -0.0003,
        -0.0003, -0.0003, -0.0003, -0.0003, -0.0003, -0.0003, -0.0002, -0.0002,
        -0.0002, -0.0002, -0.0002, -0.0002, -0.0002, -0.0002, -0.0002, -0.0002,
        -0.0002, -0.0002])
tensor([[0.7734, 0.6049, 0.3308, 0.5838, 0.8642],
        [0.7552, 0.6083, 0.1848, 0.7343, 1.0000],
        [0.7466, 0.6601, 0.2280, 0.6872, 0.7655],
        [0.7407, 0.6918, 0.2111, 0.4543, 0.8197],
        [0.7236, 0.6363, 0.3522, 0.6055, 1.0000],
        [0.7134, 0.4117, 0.3707, 0.6472, 0.7746],
        [0.7100, 0.2754, 0.2732, 0.3822, 0.8524],
        [0.6933, 0.6444, 0.2677, 0.3355, 0.6566],
        [0.6790, 0.5314, 0.1074, 0.5342, 0.6827],
        [0.6471, 0.6901, 0.0000, 0.3358, 0.

In [ ]:
import matplotlib.pyplot as plt

plt.plot(results)

In [ ]:
correct = 0.
total = 0.

for images, labels in test_loader:
    images = Variable(images.view(-1, 28*28)).cuda()
    outputs = model(images)
    _, predicted = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct+= (predicted.cpu() == labels).sum()

accuracy = 100 * correct.float() / total

In [ ]:
accuracy